name:                haskell-em
version:             0.1.0.0
github:              "deNsuh/haskell-em"
license:             BSD3
author:              "Dan Suh"
maintainer:          "kaehops@gmail.com"
copyright:           "2018 Dan Suh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deNsuh/haskell-em#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- bytestring

library:
  source-dirs: src

executables:
  haskell-em-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-em

tests:
  haskell-em-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-em
